name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_ubuntu-latest:

    runs-on: ubuntu-latest
    container: docker pull ghcr.io/hyperk/hk-software:main
    steps:
    - uses: actions/checkout@v2
    - name: Framework build
      run: cd /usr/local/hk/ToolFrameworkCore/src/ && make
    - name: build
      run: cd /usr/local/hk/hk-DataModel && make

 
 